// Executes inside the supplied simulator's closure; uses its Three.js renderer.
let lastCandidates=[], lastFlags=[], savedExercise=null, reducedMotion=Hh, playbackDuration=16000, paused=false, dirty=true, lastRender=0, ready=false;
const defaultCamera=new R(11000,15000,18000), defaultTarget=new R(0,1100,-1500);
function status(message){gt('exercise-status').textContent=message;}
function downloadJSON(name,data){const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function report(){return {type:'ejercicio-simulado-no-pronostico',createdAt:new Date().toISOString(),scenario:ut.escenario,progress:ut.avance,parameters:{windTowardDegrees:ut.viento,assumedMarginMeters:ut.margen,ignitionLocalMeters:ut.ignicion,cellSizeMeters:Xs,seed:7},blocksInScenario:lastFlags.filter(Boolean).length,constructionRecordsInScenario:lastFlags.reduce((sum,flag,i)=>sum+(flag?Ft.manzanas[i][3]:0),0),candidates:lastCandidates.map(t=>({id:t.s.properties.id,name:t.s.properties.name,coordinates:t.s.properties.coordinates,nearbyConstructionRecords:t.demanda,reason:t.motivo,availability:'sin confirmar'})),limitations:['Ejercicio, no evento vigente ni pronóstico.','Construcciones son registros, no personas o familias.','Conteos de manzanas basados en su centro.','Incendio: máscara de celdas y margen supuesto; puntos de referencia, no evaluación completa de predios.','La autoridad y los equipos competentes verifican antes de activar.'],dataProvidedDate:'2026-10-08'};}
function stopPlayback(){Zs=null;paused=false;gt('pause-exercise').textContent='Pausar';dirty=true;}
function startPlayback(){if(!ready)return;if(reducedMotion){ut.avance=1;stopPlayback();ri(true);status('Escenario completo sin animación.');return;}ut.avance=0;Zs=performance.now();paused=false;gt('pause-exercise').textContent='Pausar';ri(true);status('Ejercicio en reproducción; avance ilustrativo, no tiempo físico.');}
function setView(view){stopPlayback();_c=null;if(view==='overview'){Hn.position.copy(defaultCamera);si.target.copy(defaultTarget);}if(view==='top'){Hn.position.set(0,24000,100);si.target.set(0,1050,-800);}if(view==='hills'){Hn.position.set(-11500,9500,9500);si.target.set(-4000,1300,-2000);}si.update();dirty=true;}
gt('pause-exercise').addEventListener('click',()=>{if(!ready)return;if(Zs!==null){Zs=null;paused=true;gt('pause-exercise').textContent='Continuar';status('Pausa. Puedes cambiar la cámara o revisar el avance.');}else if(paused){Zs=performance.now()-ut.avance*playbackDuration;paused=false;gt('pause-exercise').textContent='Pausar';status('Ejercicio en reproducción.');}dirty=true;});
gt('reset-exercise').addEventListener('click',()=>{stopPlayback();ut.avance=0;ri(true);status('Escenario reiniciado. Pulsa Simular para comenzar.');});
gt('duration-exercise').addEventListener('change',e=>{playbackDuration=Number(e.target.value);stopPlayback();status('Duración visual actualizada; no equivale a minutos reales.');});
gt('reduce-motion').checked=reducedMotion;gt('reduce-motion').addEventListener('change',e=>{reducedMotion=e.target.checked;stopPlayback();dirty=true;});
gt('render-quality').addEventListener('change',e=>{An.setPixelRatio(e.target.value==='low'?1:Math.min(devicePixelRatio,1.5));An.setSize(io.clientWidth,io.clientHeight);dirty=true;});
document.querySelectorAll('[data-view]').forEach(button=>button.addEventListener('click',()=>setView(button.dataset.view)));
gt('capture-exercise').addEventListener('click',()=>{if(!ready)return;An.render(wn,Hn);const a=document.createElement('a');a.download=`cali-${ut.escenario}-ejercicio.png`;a.href=An.domElement.toDataURL('image/png');a.click();});
gt('save-exercise').addEventListener('click',()=>{if(ut.avance!==1){status('Completa el ejercicio antes de guardar una comparación.');return;}savedExercise=report();gt('comparison-exercise').textContent=`Base: ${savedExercise.scenario} · ${so(savedExercise.blocksInScenario)} manzanas. Cambia parámetros y completa otro ejercicio para comparar.`;status('Base guardada para comparar; solo durante esta sesión.');});
gt('export-exercise').addEventListener('click',()=>{if(ut.avance!==1){status('Completa el ejercicio antes de descargar su informe.');return;}downloadJSON(`ejercicio-cali-${ut.escenario}.json`,{current:report(),baseline:savedExercise});});
const originalRi=ri;ri=function(force=false){if(!pc)return;originalRi(force);dirty=true;gt('phase-exercise').textContent=ut.avance===0?'Preparación':ut.avance<1?'Recorrido del escenario':'Revisión de candidatos';if(savedExercise&&ut.avance===1){const current=report();const comparable=savedExercise.scenario===current.scenario;gt('comparison-exercise').textContent=comparable?`Base ${so(savedExercise.blocksInScenario)} → actual ${so(current.blocksInScenario)} manzanas; diferencia ${so(current.blocksInScenario-savedExercise.blocksInScenario)}. Parámetros ilustrativos; no prueba predictiva.`:`Base ${savedExercise.scenario}: ${so(savedExercise.blocksInScenario)} · actual ${current.scenario}: ${so(current.blocksInScenario)} manzanas. Amenazas distintas; conteos no equivalen a igual impacto.`;}};
si.addEventListener('change',()=>dirty=true);
window.addEventListener('resize',()=>dirty=true);
document.addEventListener('visibilitychange',()=>{if(document.hidden){stopPlayback();status('Reproducción pausada al ocultar la vista.');}dirty=true;});
An.domElement.addEventListener('webglcontextlost',e=>{e.preventDefault();stopPlayback();status('Se perdió la vista 3D. Recarga esta pestaña; el mapa principal sigue disponible.');});
window.addEventListener('beforeunload',()=>{An.setAnimationLoop(null);si.dispose();const geometries=new Set(),materials=new Set();wn.traverse(o=>{if(o.geometry)geometries.add(o.geometry);if(o.material)(Array.isArray(o.material)?o.material:[o.material]).forEach(m=>materials.add(m));});geometries.forEach(g=>g.dispose());materials.forEach(m=>m.dispose());An.dispose();});
window.simulationDiagnostics=()=>({ready,scenario:ut.escenario,progress:ut.avance,running:Zs!==null,candidates:lastCandidates.map(t=>t.s.properties.id),blocks:lastFlags.filter(Boolean).length,drawCalls:An.info.render.calls,triangles:An.info.render.triangles});
